### ISSUE TITLE
Google翻译出现了No scheme included in URL

### ISSUE THREAD

**Issue by rh10hd** [yinan-c/alfred-translate-it#1]
谢谢大佬写的workflow，我在使用Google翻译的时候出现了如下问题，请问要怎么解决呢？还是只是我的VPN不行？Deepl翻译是正常的。感谢回复。
---
[16:35:19.538] Logging Started...
[16:35:24.755] Translate It[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.9BD1C2A4-2E64-4388-8407-34829C150EBB%3E281DAF59-4B8C-4B95-A09F-A9180C5A6F9F)] Queuing argument 's'
[16:35:25.054] Translate It[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.9BD1C2A4-2E64-4388-8407-34829C150EBB%3E281DAF59-4B8C-4B95-A09F-A9180C5A6F9F)] Script with argv 's' finished
[16:35:25.058] ERROR: Translate It[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.9BD1C2A4-2E64-4388-8407-34829C150EBB%3E281DAF59-4B8C-4B95-A09F-A9180C5A6F9F)] Code 1: Traceback (most recent call last):
  File "/Users/agony/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.9BD1C2A4-2E64-4388-8407-34829C150EBB/translate.py", line 99, in <module>
    translator = Translator()
                 ^^^^^^^^^^^^
  File "/Users/agony/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.9BD1C2A4-2E64-4388-8407-34829C150EBB/libs/googletrans/client.py", line 61, in __init__
    self.client = httpx.Client(http2=http2)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/agony/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.9BD1C2A4-2E64-4388-8407-34829C150EBB/libs/httpx/_client.py", line 467, in __init__
    proxy_map = self.get_proxy_map(proxies, trust_env)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/agony/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.9BD1C2A4-2E64-4388-8407-34829C150EBB/libs/httpx/_client.py", line 88, in get_proxy_map
    key: Proxy(url=url)
         ^^^^^^^^^^^^^^
  File "/Users/agony/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.9BD1C2A4-2E64-4388-8407-34829C150EBB/libs/httpx/_config.py", line 335, in __init__
    url = URL(url)
          ^^^^^^^^
  File "/Users/agony/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.9BD1C2A4-2E64-4388-8407-34829C150EBB/libs/httpx/_models.py", line 90, in __init__
    raise InvalidURL("No scheme included in URL.")
httpx._exceptions.InvalidURL: No scheme included in URL.

**Comment by yinan-c** [comment]
这个真不清楚，很有可能是代理的问题。我的 Google 没啥问题。
